export enum MenuType {
  STEAKS = 'STEAKS',
  CHINEESE = 'CHINEESE',
  BEVERAGES = 'BEVERAGES',
  DESSERTS = 'DESSERTS',
}

export enum DishStatus {
  COMING_SOON = 'COMING_SOON',
  AVAILABLE = 'AVAILABLE',
  UNAVAILABLE = 'UNAVAILABLE',
  DISCONTINUED = 'DISCONTINUED',
}
