export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  CONTACT_SUPPORT = 'CONTACT_SUPPORT',
  VENUE_OWNER = 'VENUE_OWNER',
  VENUE_MANAGER = 'VENUE_MANAGER',
  CUSTOMER = 'CUSTOMER',
}
export enum UserStatus {
  ACTIVE = 'ACTIVE',
  BANNED = 'BANNED',
  DEACTIVATED = 'DEACTIVATED',
  DELETED = 'DELETED',
}
