export enum VenueType {
  WEDDING = 'WEDDING',
  CONFERENCE = 'CONFERENCE',
  BIRTHDAY = 'BIRTHDAY',
}

export enum VenueStatus {
  CREATED = 'CREATED',
  ASSIGNED_TO_INSPECTOR = 'ASSIGNED_TO_INSPECTOR',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  DELETED = 'DELETED',
}
